### ISSUE TITLE
How to reproduce error rate estimation results?

### ISSUE THREAD

**Issue by nindanaoto** [zama-ai/tfhe-rs#429]
Dear maintainers,

 In your parameter definitions, you mention the error rates for the parameter sets, but how to reproduce these estimation results?
 https://github.com/zama-ai/concrete/blob/4209e3366e8eb889e83720de3dc03b85778d3cec/concrete-boolean/src/parameters/mod.rs#L79-L80

**Comment by IceTDrinker** [comment]
This issue was transferred from the concrete repository as we re-organized our products. It seems the question was answered, if you have anymore questions @nindanaoto don't hesitate to contact us on the [FHE.org discord](https://discord.fhe.org/) on the TFHE-rs channel or on our [discourse](https://community.zama.ai/c/tfhe-rs/13) 🙂

I'll close this issue
