### ISSUE TITLE
Implement Copy for shortint Ciphertexts?

### ISSUE THREAD

**Issue by j2kun** [zama-ai/tfhe-rs#816]
We occasionally want to define an array of ciphertexts using the following rust syntax:

```rust
let mut array : [Ciphertext; 8] = [default_value; 8]
```

The problem is that this syntax form requires the type of `default_value` to implement `Copy`, which the shortint Ciphertext type doesn't (but the `boolean` API does, IIRC). From the [rust docs](https://doc.rust-lang.org/reference/expressions/array-expr.html):

> If the length operand has a value greater than 1 then this requires that the type of the repeat operand is Copy or that it must be a path to a constant item.

Would it be possible to have Ciphertext implement Copy? Or else, since we really just want to instantiate a "don't care" value that we can replace later with a real ciphertext value, some sort of subclass that supports this while making other operations panic? (Excuse my rust ignorance if that suggestion makes no sense)

**Comment by IceTDrinker** [comment]
hello @j2kun 

We can’t make the shortint ciphertext Copy IIRC because it contains a vec for memory storage that is not copy, however would https://doc.rust-lang.org/nightly/core/array/fn.from_fn.html with a server_key.create_trivial(0) work for you ? If so it requires zero update to TFHE-rs I believe and should already work 🙂

let us know if it works,

cheers

**Comment by j2kun** [comment]
That is perfect! Thanks for the tip.

**Comment by IceTDrinker** [comment]
My pleasure !
