### ISSUE TITLE
Support for LUTs of varying bit widths

### ISSUE THREAD

**Issue by j2kun** [zama-ai/tfhe-rs#84]
I noticed the boolean gate API here doesn't use programmable bootstrapping, and instead only supports a few 2-bit boolean gates. Would it be possible to support general programmable bootstrapping of varying bit-widths in the front-facing API? I.e., a 3-bit LUT would take three inputs `(a, b, c)`, form the ciphertext `4*c + 2*b + a` (assuming the cleartexts are 0-1 valued), and use that as an input to an 8-entry lookup table.

I could have use for PBS on up to 6-bit LUTs, though I imagine 6 bits would be too large for a 32-bit LWE ciphertext to handle under 128-bit security params. Let me know if I'm mistaken. Either way, 2-bit, 3-bit, and 4-bit LUTs would be of great use as well. I have a variety of circuits using mixed-size LUTs (2-N where N <= 6) that I would like to benchmark with tfhe-rs, and having these LUTs would make the runtime significantly faster.

I noticed that PBS is implemented, though [the docs suggest](https://github.com/zama-ai/tfhe-rs/blob/main/tfhe/src/core_crypto/algorithms/lwe_programmable_bootstrapping.rs#L199-L230) generating LUTs as RLWE ciphertexts from an integer is manual (and it's not clear if there's a means to pad the LWE ciphertexts with an extra bit to avoid the requirement of a negacyclic LUT). Having an easy API to generate the LUT RLWE ciphertexts to pass to PBS would also make this much easier.

**Comment by jborfila** [comment]
Hey @j2kun,

You should have a look on the shortint API: you will have access to precisions up to 8 bits, to the programmable bootstrapping (PBS), and to functions automatically generating LUTs from a closure.

The major difference lies into the parameter choices: in your example, you want to encrypt Boolean messages, and have LUTs that take 3 inputs. Then, choosing the parameter set "param_message_1_carry_2" should be fine. This means that you have 1 bit for to represent messages, and 2 bits to store data (so shift and add with "4*c + 2*b + a" is possible). The automatic generation of the LUT is done with the "generate_accumulator" function.

However, shortint are using 64-bit integers to represent ciphertexts (instead of 32-bits for the Booleans). Note that the common operations (e.g., AND, OR,...) are not exactly computed in the same manner, even if both relies mainly on PBS.

**Comment by j2kun** [comment]
Closing while I look into those details. Thanks!
